---
abstract: 'Type less bootstrap'
author:
  - 'Erik Carlsson <csson@cpan.org>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-BootstrapHelpers
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  List::AllUtils: '0.07'
  Mojolicious: '5.00'
  Scalar::Util: '1.29'
  String::Trim: '0.004'
  experimental: '0.008'
  perl: '5.020000'
resources:
  bugtracker: https://github.com/Csson/p5-mojolicious-plugin-bootstraphelpers/issues
  homepage: https://github.com/Csson/p5-mojolicious-plugin-bootstraphelpers
  repository: https://github.com/Csson/p5-mojolicious-plugin-bootstraphelpers.git
version: '0.004'
