---
abstract: 'Type less bootstrap'
author:
  - 'Erik Carlsson <csson@cpan.org>'
build_requires:
  Dist::Zilla::Plugin::InsertExample::FromMojoTemplates: v0.2.0
  Dist::Zilla::Plugin::PkgVersion::Block: '0.0101'
  Dist::Zilla::Plugin::Test::CreateFromMojoTemplates: '0.05'
  Test::EOL: '1.5'
  Test::Mojo::Trim: '0.03'
  Test::More: '0.96'
  Test::Pod: '1.45'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-BootstrapHelpers
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  List::AllUtils: '0.07'
  Mojolicious: '5.00'
  Scalar::Util: '1.29'
  String::Trim: '0.004'
  experimental: '0.008'
  perl: '5.020000'
  'true': '0.18'
resources:
  bugtracker: https://github.com/Csson/p5-mojolicious-plugin-bootstraphelpers/issues
  homepage: https://github.com/Csson/p5-mojolicious-plugin-bootstraphelpers
  repository: https://github.com/Csson/p5-mojolicious-plugin-bootstraphelpers.git
version: '0.0175'
x_contributors:
  - 'Erik Carlsson <info@code301.com>'
